### ISSUE TITLE
use gnu stash

### ISSUE THREAD

**Issue by Incognito** [xavierbriand/.files2#1]
You don't need to rename your files.

    brew install stow
    mkdir ~/dotfiles
    cd dotfiles
    mkdir vim
    touch vim/.vimrc
    git add vim
    git ci -m "Adds vim files to repo"
    stow vim #Drops everything inside vim/* to ~/
    stow -D vim # Uninstalls vim files

**Comment by xavierbriand** [comment]
like I'm gonna install stow everywhere I need those files....
